name: Build and Publish

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "mks-nexus-private",
              "username": "${{ secrets.MEKOM_NEXUS_USERNAME }}",
              "password": "${{ secrets.MEKOM_NEXUS_PASSWORD }}"
            },
            {
              "id": "mks-nexus-private-snapshots",
              "username": "${{ secrets.MEKOM_NEXUS_USERNAME }}",
              "password": "${{ secrets.MEKOM_NEXUS_PASSWORD }}"
            }]

      - name: Build and validate distro
        run: mvn --batch-mode clean install -P validator
